version: "3.9"

services:
  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db_container
    image: postgres:latest
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
      POSTGRES_DB: "NoteDB"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: "example@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "postgres123"
        PGADMIN_CONFIG_SERVER_MODE: "False"
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      ports:
        - "5050:80"
      restart: unless-stopped
      depends_on:
        - db


volumes:
  postgres_data:
  pgadmin-data: